### ISSUE TITLE
Incorrect check for RTCRtpSender

### ISSUE THREAD

**Issue by SimonTolham** [twilio/ortc-adapter#3]
Hi,

The following check for RTCRtpSender browser support in the Twilio code does not work in Edge:

<code>else if (typeof RTCRtpSender) {</code>

Instead, <code>typeof RTCRtpSender</code> returns the string "undefined" which an if check will always consider true.

I think a check like the following is what was intended here:
<code>else if (typeof RTCRtpSender !== 'undefined') {</code>

Thanks,
Simon Tolham

**Comment by markandrus** [comment]
Hi, @SimonTolham. Good catch! I have updated that here 024f25579b488d736cc3bd0c3ea8c6ab5f84ff8c.

**Comment by sihumphrey** [comment]
Thanks! Why did you remove the dist? Do you have instructions on how to build for non-npm / non-bower ?  That is, is there a command I can run that will produce a single js file?

**Comment by SimonTolham** [comment]
Thanks! Why did you remove the dist though? Are there any instructions I can use to produce a single javascript file, without using bower or npm?

**Comment by markandrus** [comment]
Hi, @SimonTolham—I'm still working out how development and releasing should work on this repo, but one pattern I've seen is to generate the dist files on tagged releases (and delete them afterward). If you have any thoughts on this or pointers, please share.

Otherwise, what I will do is cut a 0.1.3 release now which includes the dist. Then you should be able to just download and include that file without npm or bower.

**Comment by SimonTolham** [comment]
Not entirely sure on best practices I'm afraid. Change looks good though - believe you can close this now. Thanks for the fast response!
